services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9080:8080"
    environment:
      # Use dynamic configuration enabled via the UI
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092

  keycloak:
    build:
      context: keycloak
      dockerfile: Dockerfile
    image: ghcr.io/heitor-galindo/cap-keycloak:1.0.0
    command:
      - start-dev
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      # Used when run the services out of docker
#      KC_HOSTNAME: localhost
      #       Used when run the services with docker-compose
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_STRICT: false
      KC_LOG_LEVEL: INFO
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    restart: always
    profiles:
      - infra

  eureka:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_DIR: EurekaServer
    image: ghcr.io/heitor-galindo/cap-eureka:1.0.0
    ports:
      - "8761:8761"
    restart: on-failure
    profiles:
      - infra

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_DIR: gateway
    image: ghcr.io/heitor-galindo/cap-gateway:1.0.0
    environment:
      EUREKA_HOST: http://eureka:8761/eureka/
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/MsSecurity
      SERVER_PORT: 8089
      SPRING_PROFILES_ACTIVE: docker
      LOG_LEVEL: INFO
      RESOURCE_ID: gateway
    ports:
      - "8089:8089"
    restart: on-failure
    profiles:
      - infra

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_DIR: UserMS
    image: ghcr.io/heitor-galindo/cap-user-service:1.0.0
    environment:
      EUREKA_HOST: http://eureka:8761/eureka/
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/MsSecurity
      KEYCLOAK_TOKEN_URI: http://keycloak:8080/realms/MsSecurity/protocol/openid-connect/token
      KEYCLOAK_ADDRESS: http://keycloak:8080/
      SPRING_PROFILES_ACTIVE: docker
      KEYCLOAK_REALM: MsSecurity
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      LOG_LEVEL: INFO
      KAFKA_HOST: kafka:29092
      SERVER_PORT: 8086
      CLIENT_SECRET: 123asd
      CLIENT_ID: user-service
      APPLICATION_NAME: user-service
      CLIENT_RESOURCE_ID: user-client
      POSTGRES_DB: msdb
      POSTGRES_USER: msuser
      POSTGRES_PASSWORD: mspassword
      POSTGRES_ADDRESS: user-database:5432
    ports:
      - "8086:8086"
    restart: on-failure
    profiles:
      - service

  operation-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_DIR: OperationMS
    image: ghcr.io/heitor-galindo/cap-operation-service:1.0.0
    environment:
      EUREKA_HOST: http://eureka:8761/eureka/
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/MsSecurity
      KEYCLOAK_TOKEN_URI: http://keycloak:8080/realms/MsSecurity/protocol/openid-connect/token
      SERVER_PORT: 8088
      CLIENT_SECRET: 123asd
      CLIENT_ID: user-service
      APPLICATION_NAME: operation-service
      CLIENT_RESOURCE_ID: user-client
      SPRING_PROFILES_ACTIVE: docker
      LOG_LEVEL: INFO
      POSTGRES_DB: msdb
      POSTGRES_USER: msuser
      POSTGRES_PASSWORD: mspassword
      KAFKA_HOST: kafka:29092
      POSTGRES_ADDRESS: operation-database:5432
    ports:
      - "8088:8088"
    restart: on-failure
    profiles:
      - service

  account-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_DIR: AccountMS
    image: ghcr.io/heitor-galindo/cap-account-service:1.0.0
    environment:
      EUREKA_HOST: http://eureka:8761/eureka/
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/MsSecurity
      KEYCLOAK_TOKEN_URI: http://keycloak:8080/realms/MsSecurity/protocol/openid-connect/token
      SERVER_PORT: 8084
      APPLICATION_NAME: account-service
      CLIENT_RESOURCE_ID: user-client
      SPRING_PROFILES_ACTIVE: docker
      LOG_LEVEL: INFO
      KAFKA_HOST: kafka:29092
      POSTGRES_DB: msdb
      POSTGRES_USER: msuser
      POSTGRES_PASSWORD: mspassword
      POSTGRES_ADDRESS: account-database:5432
    ports:
      - "8084:8084"
    restart: on-failure
    profiles:
      - service

  kafka:
    image: apache/kafka:4.1.1
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LOG4J_LOGGER_KAFKA: INFO
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    profiles:
      - infra

  user-database:
    image: postgres:18
    environment:
      POSTGRES_DB: msdb
      POSTGRES_USER: msuser
      POSTGRES_PASSWORD: mspassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_user:/var/lib/postgresql
    restart: always
    profiles:
      - database

  account-database:
    image: postgres:18
    environment:
      POSTGRES_DB: msdb
      POSTGRES_USER: msuser
      POSTGRES_PASSWORD: mspassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_account:/var/lib/postgresql
    restart: always
    profiles:
      - database

  operation-database:
    image: postgres:18
    environment:
      POSTGRES_DB: msdb
      POSTGRES_USER: msuser
      POSTGRES_PASSWORD: mspassword
    ports:
      - "5436:5432"
    volumes:
      - postgres_data_operations:/var/lib/postgresql
    restart: always
    profiles:
      - database

volumes:
  keycloak_data:
  postgres_data_user:
  postgres_data_account:
  postgres_data_operations:
